GET 
  FILE='H:\project multivariate\Discriminant Analysis.sav'. 
DATASET NAME DataSet1 WINDOW=FRONT. 
DISCRIMINANT 
  /GROUPS=location(0 1) 
  /VARIABLES=x1 x2 x3 x4 x5 x6 x7 x8 x9 
  /ANALYSIS ALL 
  /SAVE=CLASS SCORES PROBS 
  /METHOD=WILKS 
  /FIN=3.84 
  /FOUT=2.71 
  /PRIORS EQUAL 
  /HISTORY 
  /STATISTICS=MEAN STDDEV UNIVF BOXM COEFF RAW CORR TABLE CROSSVALID 
  /PLOT=COMBINED 
  /CLASSIFY=NONMISSING POOLED.